name: Crowdin Translation Sync

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  Sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Crowdin Sync
        uses: crowdin/github-action@1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        with:
          localization_branch_name: 'feat/lang/service'
          create_pull_request: true
          pull_request_title: 'feat: updated translations from crowdin'
          pull_request_labels: 'priority: medium, status: ready for review, type: translation'
          pull_request_base_branch_name: 'main'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: 'src/main/resources/assets/galacticraft/lang/en_US.json'
          translation: 'src/main/resources/assets/galacticraft/lang/%locale_with_underscore%.json'
